learning_templates/basicapp/urls.py
from django.urls import path
from . import views

#TEMPLATE TAGGING
app_name = 'basicapp'

urlpatterns = [
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views

urlpatterns = [
    path('',views.index, name='index'),
    path('basicapp/',include('basicapp.urls')),
    path('admin/', admin.site.urls),
    
]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basicapp/index.html',context=context_dict)

def other(request):
    return render(request,'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relative_url_templates.html')

learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


</head>
<body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
              <a href="#" class="navbar-brand">NavBar</a>
              <button class="navbar-toggle" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggle-icon"></span>
              </button>
              <div class="collpase navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="{% url 'index'%}" class="nav-link active">Home</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'admin:index' %}" class="nav-link ">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'basicapp:other' %}" class="nav-link ">Other</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'basicapp:relative' %}" class="nav-link">Relative</a>
                        </li>
                    </ul>
              </div>
          </div>
      </nav>
      <div class="container">
          {% block body_block %}
          <!-- anything outside this will be inherited if you extend -->
          {% endblock %}
      </div>




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

learning_templates/templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
    {% block body_block %}
    <h1>Welcome to index</h1>
    <h2>This is index.html page showing!</h2>
    <h1>{{ text|cut:'hell' }}</h1>
    <h1>{{ number|add:'99' }}</h1>
    
    
    {% endblock %}

learning_templates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
    {% block body_block %}
    <h1>Welcome of other</h1>
    <h2>This is an example of template inheritence</h2>
    {% endblock %}

learning_templates/templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
{% extends "basicapp/other.html" %}
    {% block body_block %}
    <a href="{% url 'basicapp:other' %}">THE OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">admin</a>
    <a href="{% url 'index' %}">home</a>
    {% endblock %}